-- MySQL Script generated by MySQL Workbench
-- 10/09/17 15:40:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema magnet_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema magnet_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `magnet_db` DEFAULT CHARACTER SET utf8 ;
USE `magnet_db` ;

-- -----------------------------------------------------
-- Table `magnet_db`.`magnet_design_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`magnet_design_table` (
  `design_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL COMMENT '一级分类 B Q S  H',
  `family` INT NULL COMMENT '二级分类 不同长度等等',
  `design_name` VARCHAR(45) NULL COMMENT 'type+family',
  `design_by` VARCHAR(45) NULL COMMENT '设计人',
  `approved_by` VARCHAR(45) NULL COMMENT '审核人',
  `remark` VARCHAR(255) NULL,
  PRIMARY KEY (`design_id`))
ENGINE = InnoDB
COMMENT = '铁心磁铁设计';


-- -----------------------------------------------------
-- Table `magnet_db`.`device_info_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`device_info_table` (
  `device_id` INT NOT NULL COMMENT '设备总序号\n',
  `design_id` INT NULL COMMENT '对应的物理设计',
  `number` INT NULL COMMENT '统计现有同种designid的数量',
  `device_name` VARCHAR(45) NULL COMMENT 'type+family+number',
  `weight` DOUBLE NULL COMMENT '重量',
  `series` VARCHAR(45) NULL COMMENT '生产序号',
  `date_of_manu` DATETIME NULL COMMENT '生产日期',
  `designed_by` VARCHAR(45) NULL COMMENT '设计单位',
  `manu_by` VARCHAR(45) NULL COMMENT '制造单位',
  `description` VARCHAR(255) NULL COMMENT '其他',
  PRIMARY KEY (`device_id`),
  INDEX `FK_device_info_megnet_design_idx` (`design_id` ASC),
  UNIQUE INDEX `device_name_UNIQUE` (`device_name` ASC),
  CONSTRAINT `FK_megnet_design_to_device_info`
    FOREIGN KEY (`design_id`)
    REFERENCES `magnet_db`.`magnet_design_table` (`design_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magnet_db`.`rot_coil_system_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`rot_coil_system_table` (
  `rot_coil_run_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NULL COMMENT '测试序号',
  `polarity` INT NULL,
  `filename` VARCHAR(45) NULL,
  `given_current` DOUBLE NULL,
  `actual_current` DOUBLE NULL,
  `gain` VARCHAR(45) NULL,
  `start_position` DOUBLE NULL,
  `rotation_rate` DOUBLE NULL,
  `r_ref` DOUBLE NULL,
  `dx` DOUBLE NULL,
  `dy` DOUBLE NULL,
  `dz` DOUBLE NULL,
  `measure_content` VARCHAR(45) NULL,
  `meas_date` DATE NULL,
  `meas_by` VARCHAR(45) NULL,
  `meas_at` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`rot_coil_run_id`),
  INDEX `FK_RCS_to_device_idx` (`device_id` ASC),
  CONSTRAINT `FK_RCS_to_device`
    FOREIGN KEY (`device_id`)
    REFERENCES `magnet_db`.`device_info_table` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magnet_db`.`hall_probe_system_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`hall_probe_system_table` (
  `hall_probe_run_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NULL,
  `current` DOUBLE NULL,
  `water_gage` DOUBLE NULL,
  `meas_date` DATE NULL,
  `meas_by` VARCHAR(45) NULL,
  `meas_at` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`hall_probe_run_id`),
  INDEX `FK_hall_to_device_idx` (`device_id` ASC),
  CONSTRAINT `FK_hall_to_device`
    FOREIGN KEY (`device_id`)
    REFERENCES `magnet_db`.`device_info_table` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magnet_db`.`stretched_wire_system_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`stretched_wire_system_table` (
  `sw_run_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NULL,
  `sampling_rate` DOUBLE NULL,
  `speed` DOUBLE NULL,
  `accelerated_speed` DOUBLE NULL,
  `distance` DOUBLE NULL,
  `start_EX0` DOUBLE NULL,
  `start_EY0` DOUBLE NULL,
  `strain` DOUBLE NULL,
  `current` DOUBLE NULL,
  `cut_off_frequency` DOUBLE NULL,
  `meas_by` VARCHAR(45) NULL,
  `meas_date` DATE NULL,
  `meas_at` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`sw_run_id`),
  INDEX `FK_sws_to_device_idx` (`device_id` ASC),
  CONSTRAINT `FK_sws_to_device`
    FOREIGN KEY (`device_id`)
    REFERENCES `magnet_db`.`device_info_table` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magnet_db`.`magnet_design_requirement_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`magnet_design_requirement_table` (
  `design_id` INT NOT NULL,
  `length` DOUBLE NULL COMMENT '有效长度',
  `aperture` DOUBLE NULL COMMENT '磁铁孔径',
  `minimum_gap` DOUBLE NULL COMMENT '相邻磁极最小间隙',
  `useful_field` DOUBLE NULL COMMENT '好场区范围',
  `intensity_B` DOUBLE NULL COMMENT '中心磁场强度(二极铁B0,四极铁中心磁场梯度G0,六极铁中心二阶磁场梯度)',
  `intensity_Q` DOUBLE NULL COMMENT '中心磁场强度(二极铁B0,四极铁中心磁场梯度G0,六极铁中心二阶磁场梯度)',
  `intensity_S` DOUBLE NULL COMMENT '中心磁场强度(二极铁B0,四极铁中心磁场梯度G0,六极铁中心二阶磁场梯度)',
  `intensity_O` DOUBLE NULL COMMENT '中心磁场强度(二极铁B0,四极铁中心磁场梯度G0,六极铁中心二阶磁场梯度)',
  `system_component` DOUBLE NULL COMMENT '系统分量',
  `non_system_component` DOUBLE NULL COMMENT '非系统分量',
  PRIMARY KEY (`design_id`),
  CONSTRAINT `FK_requirement_to_design`
    FOREIGN KEY (`design_id`)
    REFERENCES `magnet_db`.`magnet_design_table` (`design_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '铁心磁铁设计';


-- -----------------------------------------------------
-- Table `magnet_db`.`magnet_design_parameter_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`magnet_design_parameter_table` (
  `design_id` INT NOT NULL,
  `offset` DOUBLE NULL COMMENT '偏移量',
  `ampere_turns` DOUBLE NULL COMMENT '励磁安匝数',
  `ampere_turns_each` DOUBLE NULL COMMENT '每磁极线圈匝数',
  `current` DOUBLE NULL COMMENT '励磁电流',
  `wire` VARCHAR(45) NULL COMMENT '导线规格',
  `current_density` DOUBLE NULL COMMENT '电流密度',
  `wire_length` DOUBLE NULL COMMENT '磁铁导线总长度',
  `resistance` DOUBLE NULL COMMENT '磁铁总电阻',
  `inductance` DOUBLE NULL COMMENT '磁铁电感',
  `voltage` DOUBLE NULL COMMENT '励磁电压',
  `consumption` DOUBLE NULL COMMENT '磁铁功耗',
  `c_pressure_drop` DOUBLE NULL COMMENT '冷却水压降',
  `c_channel_num` DOUBLE NULL COMMENT '并联水路数',
  `c_velocity` DOUBLE NULL COMMENT '冷却水流速',
  `c_flow` DOUBLE NULL COMMENT '冷却水流量',
  `c_temp` DOUBLE NULL COMMENT '水温升',
  `core_length` DOUBLE NULL COMMENT '铁芯长度',
  `core_section` DOUBLE NULL COMMENT '铁芯截面尺寸',
  `core_weight` DOUBLE NULL COMMENT '铁芯重',
  `copper_weight` DOUBLE NULL COMMENT '铜重',
  `physics_plot` VARCHAR(45) NULL COMMENT '物理设计报告',
  `mechanical_plot` VARCHAR(45) NULL COMMENT '机械设计报告',
  PRIMARY KEY (`design_id`),
  CONSTRAINT `FK_parameter_to_design`
    FOREIGN KEY (`design_id`)
    REFERENCES `magnet_db`.`magnet_design_table` (`design_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '铁心磁铁设计';


-- -----------------------------------------------------
-- Table `magnet_db`.`rcs_data_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`rcs_data_table` (
  `data_id` INT NOT NULL AUTO_INCREMENT,
  `run_id` INT NULL,
  `phi` DOUBLE NULL,
  `angle` DOUBLE NULL,
  `bn/b2` DOUBLE NULL,
  `bn` DOUBLE NULL,
  `an` DOUBLE NULL,
  PRIMARY KEY (`data_id`),
  INDEX `FK_data_to_rcs_idx` (`run_id` ASC),
  CONSTRAINT `FK_data_to_rcs`
    FOREIGN KEY (`run_id`)
    REFERENCES `magnet_db`.`rot_coil_system_table` (`rot_coil_run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magnet_db`.`hall_data_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`hall_data_table` (
  `data_id` INT NOT NULL AUTO_INCREMENT,
  `run_id` INT NULL,
  `current` DOUBLE NULL,
  `x` DOUBLE NULL,
  `y` DOUBLE NULL,
  `gl` DOUBLE NULL,
  `bl` DOUBLE NULL,
  PRIMARY KEY (`data_id`),
  INDEX `FK_data_to_hall_idx` (`run_id` ASC),
  CONSTRAINT `FK_data_to_hall`
    FOREIGN KEY (`run_id`)
    REFERENCES `magnet_db`.`hall_probe_system_table` (`hall_probe_run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magnet_db`.`sws_data_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`sws_data_table` (
  `data_id` INT NOT NULL AUTO_INCREMENT,
  `run_id` INT NULL,
  `raw_data` MEDIUMTEXT NULL,
  `analysis_data` MEDIUMTEXT NULL,
  PRIMARY KEY (`data_id`),
  INDEX `FK_data_to_sws_idx` (`run_id` ASC),
  CONSTRAINT `FK_data_to_sws`
    FOREIGN KEY (`run_id`)
    REFERENCES `magnet_db`.`stretched_wire_system_table` (`sw_run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magnet_db`.`hall_data_all_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`hall_data_all_table` (
  `data_id` INT NOT NULL AUTO_INCREMENT,
  `run_id` INT NULL,
  `raw_data` MEDIUMTEXT NULL,
  `analysis_data` MEDIUMTEXT NULL,
  PRIMARY KEY (`data_id`),
  INDEX `FK_data_to_sws0_idx` (`run_id` ASC),
  CONSTRAINT `FK_data_to_hall1`
    FOREIGN KEY (`run_id`)
    REFERENCES `magnet_db`.`hall_probe_system_table` (`hall_probe_run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magnet_db`.`rcs_data_all_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`rcs_data_all_table` (
  `data_id` INT NOT NULL AUTO_INCREMENT,
  `run_id` INT NULL,
  `raw_data` MEDIUMTEXT NULL,
  `analysis_data` MEDIUMTEXT NULL,
  PRIMARY KEY (`data_id`),
  INDEX `FK_data_to_rcs1_idx` (`run_id` ASC),
  CONSTRAINT `FK_data_to_rcs1`
    FOREIGN KEY (`run_id`)
    REFERENCES `magnet_db`.`rot_coil_system_table` (`rot_coil_run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `magnet_db`.`design_othesr_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `magnet_db`.`design_othesr_table` (
  `index` INT NULL AUTO_INCREMENT,
  `design_id` INT NOT NULL,
  `property` VARCHAR(45) NULL,
  `value_num` DOUBLE NULL,
  `value_text` VARCHAR(45) NULL,
  PRIMARY KEY (`index`),
  INDEX `FK_other_to_design_idx` (`design_id` ASC),
  CONSTRAINT `FK_other_to_design`
    FOREIGN KEY (`design_id`)
    REFERENCES `magnet_db`.`magnet_design_table` (`design_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
